# Generated by Django 5.1.7 on 2025-03-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_task_due_date_alter_task_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='expirationDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, default='sooner', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, default='created', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='updateDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
